# Generated by Django 4.2.2 on 2023-10-08 00:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utente', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('assunto', models.CharField(max_length=100)),
                ('nota', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Diferido', 'Diferido'), ('Sem Diferimento', 'Sem Diferimento'), ('Gabinete do Director', 'Gabinete do Director')], default='Sem Diferimento', max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utente', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('nota', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Busca', 'Busca'), ('Pendente', 'Pendente'), ('Digitalizado', 'Digitalizado'), ('Assinatura', 'Assinatura'), ('Pronto a Levantar', 'Pronto a Levantar'), ('Concluido', 'Concluido')], default='Busca', max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utente', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('observacao', models.CharField(choices=[('Secretária', 'Secretátria'), ('Sistema', 'Sistema')], max_length=50, verbose_name='Observação')),
                ('nota', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Busca', 'Busca'), ('Pendente', 'Pendente'), ('Digitalizado', 'Digitalizado'), ('Assinatura', 'Assinatura'), ('Pronto a Levantar', 'Pronto a Levantar'), ('Concluido', 'Concluido')], default='Busca', max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
        ),
    ]
