# Generated by Django 4.2.2 on 2023-12-10 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_certificado_nota_alter_declaracao_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticao',
            name='numero_peticao',
            field=models.IntegerField(default=1, verbose_name='Número do Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificado',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nome_utente',
            field=models.CharField(max_length=200, verbose_name='Nome do Utente'),
        ),
        migrations.AlterField(
            model_name='declaracao',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='declaracao',
            name='nome_utente',
            field=models.CharField(max_length=200, verbose_name='Nome do Utente'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='nome_utente',
            field=models.CharField(max_length=200, verbose_name='Nome do Utente'),
        ),
        migrations.AlterField(
            model_name='peticao',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='peticao',
            name='nome_utente',
            field=models.CharField(max_length=200, verbose_name='Nome do Utente'),
        ),
    ]
