# Generated by Django 4.2.2 on 2023-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_peticao_numero_peticao_alter_certificado_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='bi',
            field=models.CharField(default=2, max_length=14, verbose_name='Bilhete de Identidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracao',
            name='bi',
            field=models.CharField(default=3, max_length=14, verbose_name='Bilhete de Identidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='bi',
            field=models.CharField(default=1, max_length=14, verbose_name='Bilhete de Identidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificado',
            name='observacao',
            field=models.CharField(choices=[('Secretária', 'Secretária'), ('Sistema', 'Sistema')], max_length=50, verbose_name='Observação'),
        ),
    ]
