# Generated by Django 4.2.2 on 2023-12-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_levantamento_certificado_levantamento_declaracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levantamento_certificado',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='levantamento_certificado',
            name='parentesco',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Irmão(ã)', 'Irmão(ã)'), ('Tio(a)', 'Tio(a)'), ('Amigo', 'Amigo'), ('Outros', 'Outros')], max_length=50, verbose_name='Grau de Parentesco'),
        ),
        migrations.AlterField(
            model_name='levantamento_declaracao',
            name='parentesco',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Irmão(ã)', 'Irmão(ã)'), ('Tio(a)', 'Tio(a)'), ('Amigo', 'Amigo'), ('Outros', 'Outros')], max_length=50, verbose_name='Grau de Parentesco'),
        ),
        migrations.AlterField(
            model_name='levantamento_historico',
            name='parentesco',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Irmão(ã)', 'Irmão(ã)'), ('Tio(a)', 'Tio(a)'), ('Amigo', 'Amigo'), ('Outros', 'Outros')], max_length=50, verbose_name='Grau de Parentesco'),
        ),
    ]
