# Generated by Django 4.2.2 on 2023-12-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_levantamento_certificado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levantamento_certificado',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
    ]
