# Generated by Django 4.2.2 on 2023-10-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('bi', models.CharField(max_length=14, null=True)),
                ('contato1', models.IntegerField(max_length=9, null=True)),
                ('contato2', models.IntegerField(max_length=9, null=True)),
                ('imagem', models.ImageField(default='\\img\\img.jpg', upload_to='img/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
